---
strategy: webhook
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
framework_version: 2.3.7
serverless_language: 
polling_url: ''
polling_headers: ''
polling_body: ''
id: 267013
name: Shortcuts Calendar
refresh_interval: 15
